CREATE TABLE companies (
	company_id SERIAL PRIMARY KEY,
	name VARCHAR(128),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE users (
	user_id SERIAL PRIMARY KEY,
	email VARCHAR(256),
	password VARCHAR(128),
	name VARCHAR(128),
	role_code VARCHAR(20),
	company_id INTEGER,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT fk_users_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE temp_users (
	uuid VARCHAR(36) PRIMARY KEY,
	email VARCHAR(256),
	password VARCHAR(128),
	name VARCHAR(128),
	role_code VARCHAR(20),
	company_id INTEGER,
	company_name VARCHAR(128),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
	role_code VARCHAR(20) PRIMARY KEY,
	name VARCHAR(10),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stocks (
	stock_id SERIAL PRIMARY KEY,
	version INTEGER,
	optional_code CHAR(10),
	name VARCHAR(40),
	quantity INTEGER,
	reorder_point INTEGER,
	storage_location VARCHAR(60),
	company_id INTEGER,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT fk_stocks_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE receivings (
	receiving_id SERIAL PRIMARY KEY,
	quantity INTEGER,
	stock_id INTEGER,
	CONSTRAINT fk_receivings_stock_id FOREIGN KEY (stock_id) REFERENCES stocks (stock_id) ON DELETE CASCADE
);

CREATE TABLE issuings (
	issuing_id SERIAL PRIMARY KEY,
	quantity INTEGER,
	stock_id INTEGER,
	CONSTRAINT fk_issuings_stock_id FOREIGN KEY (stock_id) REFERENCES stocks (stock_id) ON DELETE CASCADE
);