CREATE TABLE companies (
	company_id SERIAL PRIMARY KEY,
	name VARCHAR(128),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE users (
	user_id SERIAL PRIMARY KEY,
	email VARCHAR(256),
	password VARCHAR(128),
	name VARCHAR(128),
	role_code VARCHAR(20),
	company_id INTEGER,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT fk_users_company_id FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE temp_users (
	uuid VARCHAR(36) PRIMARY KEY,
	email VARCHAR(256),
	password VARCHAR(128),
	name VARCHAR(128),
	role_code VARCHAR(20),
	company_id INTEGER,
	company_name VARCHAR(128),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
	role_code VARCHAR(20) PRIMARY KEY,
	name VARCHAR(10),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);